### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'itervalues'

### ISSUE THREAD

**Issue by SamuelReinfelder** [bos/statprof.py#19]
Hi,
I tried profiling with statprof and got the error, when calling statprof.display().

I am working on Mac OS and am using python 3.4

**Comment by durin42** [comment]
I just pushed a fix for this.
